### ISSUE TITLE
mention? what does mention mean?

### ISSUE THREAD

**Issue by mengxzh15** [rajeevyasarla/Syn2Real#10]
mention test dataset text file in the line 57 of test.py, for example

i do not know  this  'mention' means what ?

**Comment by rajeevyasarla** [comment]
test.py code needs the images names to be tested. so we should test images names in a text file, and that file name should be assigned to the val_filename variable, for example below we mentioned or assigned 'val_list_SIRR.txt' to the val_filename variable.
```
val_filename = 'val_list_SIRR.txt'
```
