### ISSUE TITLE
Test result problems about DDN_SIRR_with_GP

### ISSUE THREAD

**Issue by ghost** [rajeevyasarla/Syn2Real#12]
Hi, I train the model with 
the 9100 pairs of images in the original dataset of Fu et al. [9] as the labeled image, the 147 images in real_input_split1.txt as the unlabeled image and the SIRR_test.txt as the val_filename; 
but when I test the trained model on pictures in data/test/derain/SIRR_test, there are still some obvious white rain streaks on the SIRR_test, and the visual quality of test using retrained model (val_ssim is about 0.86) is much worser than using the DDN_SIRR_with_GP derain_best provided in the project(val_ssim is about 0.91).
Thank you very much!

**Comment by rajeevyasarla** [comment]
SSIM values computed using python library values are less. I used Matlab to compute SSIM values.
