### ISSUE TITLE
A question for the inference phase

### ISSUE THREAD

**Issue by zhshi0816** [rajeevyasarla/Syn2Real#13]
Hi,

Thanks for your contributions to the deraining research area. After going through the details of your work, I have a question about your algorithm. I notice that your real-world test dataset is the same as the real-world train dataset. My question is if I give you a new real-world rainy dataset, do you need to retrain the network? Or you can directly predict the results.

Looking forward to hearing from you.

Thanks.

**Comment by rajeevyasarla** [comment]
Yes, by retraining the network you might get better results. 
But, as it already trained on real rainy images, if they new rainy images are similar to the existing ones then no need of retraining
