### ISSUE TITLE
HI,It is not convenient to download the datasets in China

### ISSUE THREAD

**Issue by Jackyinuo** [rajeevyasarla/Syn2Real#14]
, so can you send a download link  summarizing  DIDMDN , Rain800, JORDER_200L, DDN  ?

**Comment by rajeevyasarla** [comment]
download data from following pages,
DID-data: https://github.com/hezhangsprinter/DID-MDN
DDN-data: https://xueyangfu.github.io/projects/cvpr2017.html
SPA-data: https://arxiv.org/pdf/1904.01538
https://github.com/nnUyi/DerainZoo/blob/master/DerainDatasets.md
