### ISSUE TITLE
The ground truth of unlabeled data.

### ISSUE THREAD

**Issue by Cassieyy** [rajeevyasarla/Syn2Real#15]
Thanks for ur great job!  
In the deblur task, i want to know what is the gt of the unlabeled sample during the unlabeled phase, i.e., in line 232th of "train.py".
Hope for your reply! Thanks in advance.

**Comment by rajeevyasarla** [comment]
For unlabeled phase we passed the same input rainy image as "gt" since we don't have the ground-truth for the input image
