### ISSUE TITLE
How can i speed up the training period?

### ISSUE THREAD

**Issue by Cassieyy** [rajeevyasarla/Syn2Real#16]
Hiiiiii, thanks for ur great job! i encounterd with the issue that the training time is too long(about 10h an epoch in deblur task) and i want to konw how can i speed up the training period. BTW, i want to konw how long about ur training time. 
Looking forward for ur reply! thanks in advance!

**Comment by rajeevyasarla** [comment]
we are planning to release a slightly faster version very soon

**Comment by Cassieyy** [comment]
Thanks for your kind reply, and waiting for it!!!

**Comment by rajeevyasarla** [comment]
GP_new_fast.py contains fast version of GP
