### ISSUE TITLE
About other dataset

### ISSUE THREAD

**Issue by jjb202** [rajeevyasarla/Syn2Real#19]
Can you provide the DID-Data、DDN-Data and SPA-Data on psnr/ssim result?

**Comment by rajeevyasarla** [comment]
download data from following pages,
DID-data: https://github.com/hezhangsprinter/DID-MDN
DDN-data: https://xueyangfu.github.io/projects/cvpr2017.html
SPA-data: https://arxiv.org/pdf/1904.01538
