### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/train/derain/DDN_100_split1.txt'

### ISSUE THREAD

**Issue by niniua** [rajeevyasarla/Syn2Real#20]
which datasets

**Comment by rajeevyasarla** [comment]
download data from following pages,
DID-data: https://github.com/hezhangsprinter/DID-MDN
DDN-data: https://xueyangfu.github.io/projects/cvpr2017.html
SPA-data: https://arxiv.org/pdf/1904.01538
https://github.com/nnUyi/DerainZoo/blob/master/DerainDatasets.md

and  arrange the data in the following format,

   .
    ├── data 
    |   ├── train # Training  
    |   |   ├── derain        
    |   |   |   ├── <dataset_name>   
    |   |   |   |   ├── rain              # rain images 
    |   |   |   |   └── norain            # clean images
    |   |   |   └── dataset_filename.txt
    |   └── test  # Testing
    |   |   ├── derain         
    |   |   |   ├── <dataset_name>          
    |   |   |   |   ├── rain              # rain images 
    |   |   |   |   └── norain            # clean images
    |   |   |   └── dataset_filename.txt
