### ISSUE TITLE
there is an error when i run the rode 

### ISSUE THREAD

**Issue by ulen2000** [rajeevyasarla/Syn2Real#4]
<img width="958" alt="360截图18430708778094" src="https://user-images.githubusercontent.com/58459187/88764093-ebdb1000-d1a6-11ea-86cc-22bd662eee48.png">

as the image shows

**Comment by rajeevyasarla** [comment]
`if category == 'derain':
    val_data_dir = './data/test/derain/'
elif category == 'dehaze':
    val_data_dir = './data/test/dehaze/'
else:
    raise Exception('Wrong image category. Set it to derain or dehaze dateset.')`

the above lines in test.py sets the test directory path depending on the category. 
`val_filename = 'SIRR_test.txt'`
the above line sets test dataset list of images, i.e the text file should contain the list of test images. For example, check "./data/test/derain/" folder for test set and and its corresponding text file.

I think in the image you are referring the text file is empty. So the image name is '' (i.e empty), that's the reason you got the above error. For better understanding of how image is loaded you can train_data.py and val_data.py files
