### ISSUE TITLE
Dataset Details (DDN-SIRR)

### ISSUE THREAD

**Issue by kylin013** [rajeevyasarla/Syn2Real#5]
Hi, according to the paper, for the dataset DDN-SIRR, 9100 pairs of synthesized images and some real-world images are used as the training set, and another 20 pairs as testing set.  I have some questions as follows:

1. How many real-world images are in the training set? Are the 147 images in the path 'Syn2Real/data/train/derain/real_input/'?
2. The original dataset  of Fu _et al._ [9] consists of 9100 training pairs and 4900 testing pairs, did you use the 4900 pairs for testing?
3. Could you share the data split file for the 9100 training pairs, since the ratio has been updated to 12600:1400 on their official websit.

Thank you very much!

**Comment by rajeevyasarla** [comment]
Hi @kylin013 ,

1. yes, we used 147 real-world images in the training set as unlabelled data set, and they are provided in "./data/train/derain/real_input/"
2. Yes, the original dataset of Fu et al. [9] consists of 9100 training pairs and 4900 testing pairs, in this publication we didn't use 4900 pairs for testing.
3. updated dataset of  Fu et al. [9]  consists of 12600:1400 training: testing split. their dataset is created using 14 rain streaks for each image, so using 1000 images a total of 14000 images were created and split into training and testing. Earlier I think images index with 1 to 650 were used for training and rest for testing. In the updated dataset images indexed with 1to 900 are used as training and 901 to 1000 are for testing. So in our training processes we used images indexed with 1to 650 as labelled dataset in our training.

**Comment by kylin013** [comment]
Hi @rajeevyasarla , thanks so much for your reply! I still have a question, did you use the 20 images in "./data/test/derain/SIRR_test/" for both validation and testing, and which 10 of them are dense (or sparse)?

**Comment by rajeevyasarla** [comment]
Hi @kylin013 , Yes I use 20 images "./data/test/derain/SIRR_test/" for testing where 10 are dense and 10 are sparse

**Comment by kylin013** [comment]
Hi @rajeevyasarla , which 10 images are dense? the images index with 1 to 10?

**Comment by rajeevyasarla** [comment]
Hi @kylin013 , images indexed from 1 to 10 are dense, and 11-20 are sparse
