### ISSUE TITLE
Can you provide all the test data of synthetic rain image and real rain image after rain?

### ISSUE THREAD

**Issue by FUNGERN** [rajeevyasarla/Syn2Real#6]
I am very happy that you have made so many contributions. Can you provide all the data for the test after the rain with the synthetic rain image and the real rain image?

**Comment by rajeevyasarla** [comment]
Hi @FUNGERN ,

test for synthetic is provided in "data/test/derain/SIRR_test/" folder,
for real rain images test data is provided in "data/test/derain/real_input" folder

**Comment by FUNGERN** [comment]
Hello, I used your model to remove the rain from the real image. The effect of removing the rain is as follows. I want to perform 100 tests on the synthetic image data set Rain100H, and found that the rain removal effect is not ideal, as shown in the figure below. Could you please explain if I did it unreasonably? thank
![1](https://user-images.githubusercontent.com/49382317/89860174-77a46180-dbd5-11ea-82df-a89581b08f2f.jpg)
![QQ截图20200811131651](https://user-images.githubusercontent.com/49382317/89860180-7d01ac00-dbd5-11ea-82f7-2682b466d41e.jpg)
