### ISSUE TITLE
About metrics of NIQE and BRISQUE

### ISSUE THREAD

**Issue by hhb072** [rajeevyasarla/Syn2Real#9]
Thank you very much for your answer to my previous question about the real dataset. 

Now I am confused by the non-reffereced metrics of NIQE and BRISQUE.
I test them with the code found online and find the results are quite different with those in your paper, even for the input real rainy images. The reason may be the uncorrect or different implementations of computing them.

So I am wondering if you can release the test code or provide an accesible link of the calculation of these two metrics.
Thanks again for your kindness.

**Comment by rajeevyasarla** [comment]
I used Matlab2019a version, and specifically i used matlab's inbuilt functions to compute niqe and brisque scores. I resized all the images to 512x512 size and computed the values

**Comment by hhb072** [comment]
Thank you very much!
